### ISSUE TITLE
Having these three errors in unity 5.2.3

### ISSUE THREAD

**Issue by RYG81** [JasonH234/Unity-SVG-Renderer#1]
Assets/SVGPolygon.cs(132,43): error CS0246: The type or namespace name `Edge' could not be found. Are you missing a using directive or an assembly reference?

Assets/SVGPolygon.cs(105,16): error CS0246: The type or namespace name `Edge' could not be found. Are you missing a using directive or an assembly reference?

Assets/SVGElement.cs(14,5): error CS0246: The type or namespace name `HexConverter' could not be found. Are you missing a using directive or an assembly reference?
any suggestion on fixing this?

**Comment by JasonH234** [comment]
Sorry, this is because it was intended to provide an example of how to create an SVG Renderer with sample code - but not be the full solution (which is why it only contains the SVG Polygon type, for example).
I have added the Edge class into the sample, and you can find the HexConverter class on the Unity wiki:
http://wiki.unity3d.com/index.php?title=HexConverter
You'll also need the Triangulator:
http://wiki.unity3d.com/index.php?title=Triangulator
I hope this helps - and I'll update the description.

**Comment by JasonH234** [comment]
On reflection I've added the Triangulator and HexConverter from the Unify Wiki to the sample. If you pull the repo you should now have all the required files to create a SVG Polygon mesh. Sorry for the confusion!

**Comment by RYG81** [comment]
Thank you very much Jason.

**Comment by JasonH234** [comment]
No problem. :)

**Comment by RYG81** [comment]
How would you use it?

**Comment by RYG81** [comment]
Still there are few more issues. Check image below.
![screenshot_1](https://cloud.githubusercontent.com/assets/10570236/11362496/ee8d2db4-92b9-11e5-8128-8e20d3c4b790.png)

**Comment by JasonH234** [comment]
Sorry again, I was really busy when I created the repo so I didn't have the time to create any documentation. 

Essentially you use it by calling the importSVG method in the SVGtoMesh class with the path of an SVG file. Anything in the SVG file which isn't of the SVG polygon type will be ignored if you're running the sample code though - as the intention was that people could use the sample code as a base for implementing the rest of the SVG specification themselves. You would have to inspect the SVG file yourself to make sure it has elements to render with the <polygon> type. You could then use an XML layout to position elements around the screen as desired.

The SVG primitives (line, rect, circle, ellipse.. ) should be quite easy to implement, certainly of less complexity than the SVGPolygon class which is provided. However if you want to implement paths you will find it quite difficult! I would provide the full set of classes we developed but I don't really have the time to clean up the code or support it - I don't even know if it will work in the latest version of Unity (though I see no reason why it wouldn't). 

As for the errors, I neglected to comment out classes which haven't been included in the sample, and the txtObj error was a mistake when rearranging some of the code before uploading. These issues should be fixed in the latest, but I've reinstalled Unity and will give it a check :P

**Comment by JasonH234** [comment]
I've provided some documentation in the readme and have provided a sample project environment (including an example svg file that works with the sample code). 
Hopefully this helps.

**Comment by RYG81** [comment]
That's so nice of you Jason. Thanks for outing time behind this.
Rahul

**Comment by RYG81** [comment]
So it generates polygons at run time. Can't we create something in editor so that we can preview it while developing?

**Comment by JasonH234** [comment]
No problem. 
Could do by calling SVGtoMesh's import method from an editor script, maybe with an 'import' button attached to prompt generation in the editor as opposed to during runtime. Would definitely be useful. Wasn't something that actually came to mind when we were working on the project last year.

**Comment by RYG81** [comment]
There are two assets on assets store named easy svg and svg importer, if in case you want to check feature list. They currently the best but paid. So making something good but free is always great job. And thank you for that.

**Comment by JasonH234** [comment]
Thank you, no problem, hopefully it'll be of some use. I probably won't be able to add further features myself though, at least not in the short term, as I have a lot of work at the moment. If people find it useful then I could look into providing more content myself over summer potentially.
